name: Deploy GitHub Pages
run-name: ${{ github.workflow }} run by ${{ github.actor }}
on:
  #push:
  #  branches:
  #    - projects
  workflow_dispatch:
  
jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:    
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
